name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x ]
        platform: [ ubuntu-latest ]
    name: ${{ matrix.platform }} @ Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set environment
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test -v ./...

      - name: Update go report card
        if: success() && matrix.platform == 'ubuntu-latest'
        continue-on-error: true
        uses: creekorful/goreportcard-action@v1.0
